[meta]
name = "TrackmaniaApiObjsAndHelpers"
author = 'op-as-codegen'

[script]
defines = [ 'RELEASE' ]
shared_exports = [ 'DictOfString.as', 'Challenge.as', 'Challenges.as', 'DictOfInt.as', 'DictOfChallenge.as', 'DictOfChallenge_WriteLog.as', 'Competition.as', 'MatchResult.as', 'MatchResults.as', 'TrackOfTheDayEntry.as', 'TotdMonth.as', 'TotdResp.as', 'DictOfTrackOfTheDayEntry_WriteLog.as', 'TmMap.as', 'DictOfTmMap_WriteLog.as', 'MaybeOfUint.as' ]